steps:
    - name: gcr.io/cloud-builders/docker
      args: [build, -t, gcr.io/$PROJECT_ID/dodge-all-the-trash, .]

    - name: gcr.io/cloud-builders/gcloud
      args:
          [
              compute,
              instance-groups,
              managed,
              rolling-action,
              restart,
              dodge-all-the-trash-instance-group,
              --zone=us-central1-a,
          ]

images:
    - gcr.io/dodge-all-the-trash-275313/dodge-all-the-trash
